### ISSUE TITLE
how to send a proper json to the middleware 

### ISSUE THREAD

**Issue by bitquality** [expressjs/morgan#210] opened 2019-08-26 18:06 UTC
Hi,

I am using morgan middleware to capture required meta tags. One of them is reqBody .

```
// Hook morgan body to express app
morgan.token('reqBody', function (req: any, res: any) {
  return req.body;
  //return JSON.parse(req.body); error is thrown
});
```

But when winston configuration receives it then it gets a parse error:

```
exports.stream = {
    write: function (message: any, encoding: string) {
        let code = JSON.parse(message).status;
       info(message); //prints request_body as [object object]

}
}
```

if i just return req.body  [Object Object] not sure how i can get the object render properly.

**Comment by bitquality** [comment] 2019-09-10 14:14
Here is my format object:

`const printfFormat = format.printf(info => {
    const { timestamp, level, message, ...args } = info;
    return `[${timestamp}] [${level}]: ${message} ${Object.keys(args).length ? JSON.stringify(args, null, 4) : ''}`;
});`

**Comment by dougwilson** [comment] 2019-10-03 15:43
There is still not enough information for me to assist. Please provide a complete code I can copy and paste and run to see the issue. I am happy to go debug through it to determine what the issue is, but I'm just not able to piece it together with the information provided.

**Comment by dougwilson** [comment] 2019-11-13 14:10
Closing due to no further follow up.

**Closed by dougwilson** 2019-11-13 14:10 UTC
Labels: awaiting more info
