### ISSUE TITLE
Colored status token

### ISSUE THREAD

**Issue by MatheusFerreira71** [expressjs/morgan#260] opened 2022-01-12 18:37 UTC
When the status token is used to create custom formats, it comes in white on the console. 

Take the following example -

morgan.format(
    'custom-format',
    ':method :url :status :response-time ms - :res[content-length] - :user-agent',
  );

The status on the console will be white, no matter the status it returns.

My suggestion is to create a new token :colored-status that comes with the colors that we see on the dev format.

Thanks, hope it helps.

**Comment by dougwilson** [comment] 2022-01-12 18:41
Duplicate of #186 

Thanks for the suggestion!

**Closed by dougwilson** 2022-01-12 18:41 UTC
